export const SOCIAL_LINKS_LABELS = {
  uk: {
    title: "Соціальні мережі",
    description: "Додайте, відредагуйте або видаліть посилання",
    platformOther: "Інша мережа",
    add: "Додати",
    platform: "Платформа",
    link: "Посилання",
    item: "Елемент {index}",
    remove: "Видалити",
    emptyState: "Немає доданих соціальних мереж.",
    selectPlaceholder: "Оберіть соціальну мережу",
  },
  en: {
    title: "Social networks",
    description: "Add, edit, or remove links",
    platformOther: "Another network",
    add: "Add",
    platform: "Platform",
    link: "Link",
    item: "Item {index}",
    remove: "Remove",
    emptyState: "No social links have been added.",
    selectPlaceholder: "Select a social network",
  },
};

export const CONTACTS_LABELS = {
  uk: {
    title: "Контакти",
    description: "Додайте, відредагуйте або видаліть контакти",
    typeOther: "Інший контакт",
    add: "Додати",
    type: "Тип",
    titleContact: "Заголовок",
    link: "Контакт",
    textLink: "Текст посилання",
    item: "Елемент {index}",
    remove: "Видалити",
    emptyState: "Немає доданих контактів.",
    selectPlaceholder: "Оберіть тип контатку",
  },
  en: {
    title: "Contacts",
    description: "Add, edit or delete contacts",
    typeOther: "Other contact",
    add: "Add",
    type: "Type",
    titleContact: "Title",
    link: "Contact",
    textLink: "Link text",
    item: "Item {index}",
    remove: "Remove",
    emptyState: "No contacts have been added.",
    selectPlaceholder: "Select the type of contact",
  },
};

export const FORM_RADIO_BUTTON = {
  uk: {
    title: "Редагування грипи кнопок",
    description: "Додайте, відредагуйте або видаліть кнопки",
    platformOther: "Інша мережа",
    add: "Додати",
    titleButton: "Кнопка",
    item: "Кнопка {index}",
    remove: "Видалити",
    emptyState: "Немає доданих пунктів.",
  },
  en: {
    title: "Editing the radio button",
    description: "Add, edit or delete buttons",
    platformOther: "Another network",
    add: "Add",
    titleButton: "Link",
    item: "Button {index}",
    remove: "Remove",
    emptyState: "No items have been added.",
  },
};
